pid standalone/edge/logs/nginx.pid;
error_log standalone/edge/logs/error.log info;

events {}

http {
    access_log standalone/edge/logs/access.log;

    upstream recommendations_v1_backend {
        server 127.0.0.1:8081;
    }

    upstream recommendations_v2_backend {
        server 127.0.0.1:8082;
    }

    include k8s/shared/edge-server.conf;
}
