receivers:
  obi:
    version: "2.0"
    policy:
      default_action: exclude
    rules:
      - action: include
        match:
          process:
            open_ports: "8000"
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: localhost:14317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, obi]
      processors: [batch]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [obi]
      processors: [batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
