// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"io"
	"math"
	"sort"
	"strings"
)

const (
	maxFlakyTestsShown     = 20
	maxRecentFailuresShown = 30
	maxSnippetDisplay      = 600
	maxTestsInList         = 8
)

func writeReport(w io.Writer, title string, results []TestResult, metaMap map[string]RunMeta, repo string) error {
	if title == "" {
		title = "CI Test Analysis Report"
	}
	if len(results) == 0 && len(metaMap) == 0 {
		_, err := fmt.Fprintf(w, "# %s\n\nNo test data found for the analysis period.\n", title)
		return err
	}

	minDate, maxDate := dateRangeFromMeta(metaMap)
	tests := computeTestStats(results)
	workflows := computeWorkflowStats(results, metaMap)
	fingerprints := computeFingerprintStats(results)
	uniqueTests := countUniqueTests(tests)

	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# %s", title)
	p("")
	p("**Period:** %s to %s", minDate, maxDate)
	p("**Runs analyzed:** %d | **Tests tracked:** %d", len(metaMap), uniqueTests)
	p("")

	writeWorkflowTable(p, workflows)
	writeFlakyTestsTable(p, tests)
	writeErrorSummaryTable(p, fingerprints)
	writeFingerprintTable(p, fingerprints)
	writeRecentFailuresTable(p, results, repo)
	writeLegend(p)

	flakyTests := countUniqueTests(filterFlakyTests(tests))
	p("---")
	p("*Generated by CI Test Analysis · %d tests analyzed · %d flaky (%.0f%%)*",
		uniqueTests, flakyTests, float64(flakyTests)/math.Max(float64(uniqueTests), 1)*100)

	return nil
}

func writeWorkflowTable(p func(string, ...any), workflows []workflowStats) {
	p("## CI Reliability (main branch)")
	p("")
	p("Pass rate matches the GitHub workflow conclusion — runs that pass after a flaky retry count as passes.")
	p("")
	p("| Workflow | Runs | Clean | Flaky | Failed | Pass rate |")
	p("|----------|------|-------|-------|--------|-----------|")

	sort.Slice(workflows, func(i, j int) bool {
		ri := float64(workflows[i].runsWithFail) / math.Max(float64(workflows[i].totalRuns), 1)
		rj := float64(workflows[j].runsWithFail) / math.Max(float64(workflows[j].totalRuns), 1)
		if ri != rj {
			return ri > rj
		}
		return workflows[i].name < workflows[j].name
	})
	for _, ws := range workflows {
		passRate := 100.0
		if ws.totalRuns > 0 {
			passRate = float64(ws.totalRuns-ws.runsWithFail) / float64(ws.totalRuns) * 100
		}
		clean := ws.totalRuns - ws.runsWithFlaky - ws.runsWithFail
		p("| %s | %d | %d | %d | %d | %.0f%% |",
			ws.name, ws.totalRuns, clean, ws.runsWithFlaky, ws.runsWithFail, passRate)
	}
	p("")
}

func writeFlakyTestsTable(p func(string, ...any), tests []*testStats) {
	flaky := filterFlakyTests(tests)
	if len(flaky) == 0 {
		p("## Flaky Tests")
		p("")
		p("No flaky tests detected in this period.")
		p("")
		return
	}

	p("## Top Flaky Tests")
	p("")
	p("Tests that failed or required retries to pass, sorted by failure rate.")
	p("Counts are per workflow and per CI run — a test running in multiple shards counts once per run.")
	p("")
	p("- **Runs**: CI runs in this workflow that attempted the test (skipped runs excluded)")
	p("- **Failures**: test failed and never passed (broken)")
	p("- **Retries**: test failed initially but passed on rerun (flaky)")
	p("")
	p("| Workflow | Test | Runs | Failures | Retries | Failure rate | Primary error |")
	p("|---------|------|------|----------|---------|-------------|--------------|")

	limit := maxFlakyTestsShown
	if len(flaky) < limit {
		limit = len(flaky)
	}
	for _, ts := range flaky[:limit] {
		failPct := 0.0
		if ts.totalRuns > 0 {
			failPct = float64(ts.failed+ts.flakyPassed) / float64(ts.totalRuns) * 100
		}
		p("| %s | `%s` | %d | %d | %d | %.0f%% | %s |",
			ts.workflow, displayTestName(ts.pkg, ts.name), ts.totalRuns, ts.failed, ts.flakyPassed, failPct, primaryFingerprint(ts.fingerprints))
	}
	p("")
}

// writeErrorSummaryTable aggregates from the same per-result fingerprint data
// as the Failure Fingerprints table so the numbers are always consistent.
func writeErrorSummaryTable(p func(string, ...any), fingerprints []fingerprintStats) {
	if len(fingerprints) == 0 {
		return
	}

	p("## Failures by Error Type")
	p("")
	p("| Error | Total occurrences | Affected tests |")
	p("|-------|------------------|----------------|")
	for _, fp := range fingerprints {
		testList := formatTestList(affectedTestSlice(fp.affectedTests))
		p("| `%s` | %d | %d (%s) |", fp.fingerprint, fp.occurrences, len(fp.affectedTests), testList)
	}
	p("")
}

func writeFingerprintTable(p func(string, ...any), fingerprints []fingerprintStats) {
	if len(fingerprints) == 0 {
		return
	}

	p("## Failure Fingerprints")
	p("")
	p("Error patterns observed across all failures.")
	p("")
	p("| Pattern | Occurrences | Affected tests | Example |")
	p("|---------|------------|---------------|---------|")
	for _, fp := range fingerprints {
		testList := formatTestList(affectedTestSlice(fp.affectedTests))
		example := fp.example
		if len(example) > maxSnippetDisplay {
			example = example[:maxSnippetDisplay-3] + "..."
		}
		example = strings.ReplaceAll(example, "|", "\\|")
		example = strings.ReplaceAll(example, "\n", " ")
		p("| `%s` | %d | %d (%s) | %s |",
			fp.fingerprint, fp.occurrences, len(fp.affectedTests), testList, example)
	}
	p("")
}

func writeRecentFailuresTable(p func(string, ...any), results []TestResult, repo string) {
	var failures []failureEvent
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		failures = append(failures, failureEvent{
			runID:       r.RunID,
			workflow:    r.Workflow,
			pkg:         r.Package,
			test:        r.Test,
			fingerprint: r.ErrorFingerprint,
			snippet:     r.ErrorSnippet,
		})
	}
	if len(failures) == 0 {
		return
	}

	sort.Slice(failures, func(i, j int) bool {
		if failures[i].fingerprint != failures[j].fingerprint {
			return failures[i].fingerprint < failures[j].fingerprint
		}
		if failures[i].test != failures[j].test {
			return failures[i].test < failures[j].test
		}
		return failures[i].pkg < failures[j].pkg
	})

	p("## Failure Details")
	p("")
	p("| Run | Workflow | Test | Fingerprint | Error |")
	p("|-----|---------|------|-------------|-------|")

	limit := maxRecentFailuresShown
	if len(failures) < limit {
		limit = len(failures)
	}
	for _, rf := range failures[:limit] {
		snippet := rf.snippet
		if len(snippet) > maxSnippetDisplay {
			snippet = snippet[:maxSnippetDisplay-3] + "..."
		}
		snippet = strings.ReplaceAll(snippet, "|", "\\|")
		snippet = strings.ReplaceAll(snippet, "\n", " ")
		fp := rf.fingerprint
		if fp == "" {
			fp = "unknown"
		}
		p("| [%s](https://github.com/%s/actions/runs/%s) | %s | `%s` | `%s` | %s |",
			rf.runID, repo, rf.runID, rf.workflow, displayTestName(rf.pkg, rf.test), fp, snippet)
	}
	p("")
}

func writeLegend(p func(string, ...any)) {
	// Sorted alphabetically by pattern name.
	p("## Fingerprint Legend")
	p("")
	p("| Pattern | Description |")
	p("|---------|-------------|")
	p("| `cancelled` | Run cancelled or interrupted — typically a job-level timeout |")
	p("| `connection-refused` | Service not reachable — likely not yet started or crashed |")
	p("| `data-race` | Go race detector found a data race (`-race` flag) |")
	p("| `disk-full` | Runner ran out of disk space |")
	p("| `docker-error` | Docker daemon error — image pull, OCI runtime, or daemon connectivity |")
	p("| `exit-error` | Non-zero exit code with no more specific pattern matched |")
	p("| `oom-killed` | Process killed by signal — typically out of memory |")
	p("| `panic` | Unrecovered Go panic |")
	p("| `port-conflict` | Docker port already allocated or address in use — container startup collision |")
	p("| `timeout` | Test or context deadline exceeded |")
	p("| `unknown` | No error output captured |")
	p("| `unknown-XXXXXXXX` | Unrecognized error — hash groups identical unknown failures together |")
	p("")
}

// formatTestList renders test identities as a backticked, comma-separated
// list, truncating by count to avoid breaking markdown with partial names.
func formatTestList(ids []pkgTest) string {
	rendered := make([]string, len(ids))
	for i, id := range ids {
		rendered[i] = displayTestName(id.pkg, id.test)
	}
	sort.Strings(rendered)
	limit := len(rendered)
	if limit > maxTestsInList {
		limit = maxTestsInList
	}
	backticked := make([]string, limit)
	for i := range limit {
		backticked[i] = "`" + rendered[i] + "`"
	}
	joined := strings.Join(backticked, ", ")
	if len(rendered) > maxTestsInList {
		joined += fmt.Sprintf(" +%d more", len(rendered)-maxTestsInList)
	}
	return joined
}

type testStats struct {
	name         string
	pkg          string // part of test identity; see TestResult.Package
	workflow     string
	totalRuns    int // CI runs in which the test was attempted (passed/failed/flaky-passed)
	passed       int
	failed       int
	flakyPassed  int
	skipped      int
	fingerprints map[string]int
}

type failureEvent struct {
	runID       string
	workflow    string
	pkg         string
	test        string
	fingerprint string
	snippet     string
}

type workflowStats struct {
	name          string
	totalRuns     int
	runsWithFail  int // runs with at least one hard failure
	runsWithFlaky int // runs with flaky-passed but no hard failure
	runIDs        map[string]bool
	failedRunIDs  map[string]bool
	flakyRunIDs   map[string]bool
}

type fingerprintStats struct {
	fingerprint   string
	occurrences   int
	affectedTests map[pkgTest]bool
	example       string
}

// displayTestName renders a test identity as "pkg-leaf.TestName", or just
// "TestName" when the package is empty (job-only workflows like OATS have no
// test-level data and therefore no package). Rendering is stable per
// identity — independent of which table or scope the row appears in.
func displayTestName(pkg, name string) string {
	if pkg == "" {
		return name
	}
	if i := strings.LastIndex(pkg, "/"); i >= 0 {
		pkg = pkg[i+1:]
	}
	return pkg + "." + name
}

func dateRangeFromMeta(metaMap map[string]RunMeta) (string, string) {
	var minDate, maxDate string
	for _, rm := range metaMap {
		d := rm.CreatedAt
		if len(d) >= 10 {
			d = d[:10]
		}
		if d == "" {
			continue
		}
		if minDate == "" || d < minDate {
			minDate = d
		}
		if maxDate == "" || d > maxDate {
			maxDate = d
		}
	}
	return minDate, maxDate
}

// computeTestStats aggregates per (workflow, package, test) so each row in
// the flaky table is scoped to a single workflow — the displayed Workflow
// column always matches the Runs/Failures/Retries totals. Package is part
// of the key because unit-test shards can run multiple Go packages in one
// gotestsum file and tests sharing a name across packages must not merge.
//
// Within that scope, results are deduplicated by RunID so that a test which
// appears in multiple shards or report files contributes a single outcome per
// CI run. The per-run outcome is failed > flaky-passed > passed > skipped.
// Skipped runs are excluded from totalRuns: a skipped test wasn't attempted,
// and counting it would dilute failure rates.
func computeTestStats(results []TestResult) []*testStats {
	type statsKey struct{ workflow, pkg, test string }
	type runAggregate struct {
		outcome      string
		fingerprints map[string]int
	}

	// First pass: collapse shard-level results into one outcome per (workflow, package, test, runID).
	perRun := map[statsKey]map[string]*runAggregate{}
	for _, r := range results {
		k := statsKey{r.Workflow, r.Package, r.Test}
		if perRun[k] == nil {
			perRun[k] = map[string]*runAggregate{}
		}
		ra, ok := perRun[k][r.RunID]
		if !ok {
			ra = &runAggregate{fingerprints: map[string]int{}}
			perRun[k][r.RunID] = ra
		}
		if outcomeRank(r.Outcome) > outcomeRank(ra.outcome) {
			ra.outcome = r.Outcome
		}
		if (r.Outcome == "failed" || r.Outcome == "flaky-passed") && r.ErrorFingerprint != "" {
			ra.fingerprints[r.ErrorFingerprint]++
		}
	}

	// Second pass: aggregate per-run outcomes into per (workflow, package, test) stats.
	tests := make([]*testStats, 0, len(perRun))
	for k, runs := range perRun {
		ts := &testStats{
			name:         k.test,
			pkg:          k.pkg,
			workflow:     k.workflow,
			fingerprints: map[string]int{},
		}
		for _, ra := range runs {
			switch ra.outcome {
			case "passed":
				ts.passed++
				ts.totalRuns++
			case "failed":
				ts.failed++
				ts.totalRuns++
			case "flaky-passed":
				ts.flakyPassed++
				ts.totalRuns++
			case "skipped":
				ts.skipped++
			}
			for fp, n := range ra.fingerprints {
				ts.fingerprints[fp] += n
			}
		}
		tests = append(tests, ts)
	}
	return tests
}

// outcomeRank gives the priority used when collapsing multiple shard results
// for the same (workflow, test, runID). Higher rank wins.
func outcomeRank(o string) int {
	switch o {
	case "failed":
		return 4
	case "flaky-passed":
		return 3
	case "passed":
		return 2
	case "skipped":
		return 1
	}
	return 0
}

// countUniqueTests returns the number of distinct (package, test) identities
// across the given stats. Tests that run in multiple workflows are counted
// once. Different packages with the same test name are counted separately so
// the total isn't deflated by unit-test shards that span packages.
func countUniqueTests(tests []*testStats) int {
	seen := map[pkgTest]bool{}
	for _, ts := range tests {
		seen[pkgTest{ts.pkg, ts.name}] = true
	}
	return len(seen)
}

// computeWorkflowStats builds workflow reliability stats from both test results
// and run metadata. This ensures job-only workflows (which produce no TestResult
// entries) still appear in the reliability table.
func computeWorkflowStats(results []TestResult, metaMap map[string]RunMeta) []workflowStats {
	type runKey struct {
		workflow string
		runID    string
	}
	// Track per-run: hasFail and hasFlaky separately.
	type runState struct {
		hasFail  bool
		hasFlaky bool
	}
	runStates := map[runKey]*runState{}

	// Seed from metaMap so every collected run is represented.
	for _, rm := range metaMap {
		key := runKey{rm.Workflow, rm.RunID}
		rs := &runState{}
		// For runs without test-level data, use the run conclusion.
		switch rm.Conclusion {
		case "failure", "timed_out", "cancelled":
			rs.hasFail = true
		}
		runStates[key] = rs
	}

	// Override with test-level data when available.
	for _, r := range results {
		key := runKey{r.Workflow, r.RunID}
		rs, ok := runStates[key]
		if !ok {
			rs = &runState{}
			runStates[key] = rs
		}
		if r.Outcome == "failed" {
			rs.hasFail = true
		}
		if r.Outcome == "flaky-passed" {
			rs.hasFlaky = true
		}
	}

	wfMap := map[string]*workflowStats{}
	for key, rs := range runStates {
		ws, ok := wfMap[key.workflow]
		if !ok {
			ws = &workflowStats{
				name:         key.workflow,
				runIDs:       map[string]bool{},
				failedRunIDs: map[string]bool{},
				flakyRunIDs:  map[string]bool{},
			}
			wfMap[key.workflow] = ws
		}
		if !ws.runIDs[key.runID] {
			ws.runIDs[key.runID] = true
			ws.totalRuns++
		}
		if rs.hasFail && !ws.failedRunIDs[key.runID] {
			ws.failedRunIDs[key.runID] = true
			ws.runsWithFail++
		} else if rs.hasFlaky && !ws.flakyRunIDs[key.runID] {
			ws.flakyRunIDs[key.runID] = true
			ws.runsWithFlaky++
		}
	}

	var result []workflowStats
	for _, ws := range wfMap {
		result = append(result, *ws)
	}
	return result
}

func computeFingerprintStats(results []TestResult) []fingerprintStats {
	fpMap := map[string]*fingerprintStats{}
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		fp := r.ErrorFingerprint
		if fp == "" {
			fp = "unknown"
		}
		fs, ok := fpMap[fp]
		if !ok {
			fs = &fingerprintStats{
				fingerprint:   fp,
				affectedTests: map[pkgTest]bool{},
			}
			fpMap[fp] = fs
		}
		fs.occurrences++
		fs.affectedTests[pkgTest{r.Package, r.Test}] = true
		if fs.example == "" && r.ErrorSnippet != "" {
			fs.example = r.ErrorSnippet
		}
	}

	var result []fingerprintStats
	for _, fs := range fpMap {
		result = append(result, *fs)
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].occurrences > result[j].occurrences
	})
	return result
}

func filterFlakyTests(tests []*testStats) []*testStats {
	var flaky []*testStats
	for _, ts := range tests {
		if ts.failed > 0 || ts.flakyPassed > 0 {
			flaky = append(flaky, ts)
		}
	}
	sort.Slice(flaky, func(i, j int) bool {
		ri := float64(flaky[i].failed+flaky[i].flakyPassed) / float64(flaky[i].totalRuns)
		rj := float64(flaky[j].failed+flaky[j].flakyPassed) / float64(flaky[j].totalRuns)
		if ri != rj {
			return ri > rj
		}
		if flaky[i].workflow != flaky[j].workflow {
			return flaky[i].workflow < flaky[j].workflow
		}
		if flaky[i].name != flaky[j].name {
			return flaky[i].name < flaky[j].name
		}
		return flaky[i].pkg < flaky[j].pkg
	})
	return flaky
}

func primaryFingerprint(fps map[string]int) string {
	if len(fps) == 0 {
		return "unknown"
	}
	var best string
	bestCount := 0
	for fp, count := range fps {
		if count > bestCount || (count == bestCount && fp < best) {
			best = fp
			bestCount = count
		}
	}
	return "`" + best + "`"
}

func affectedTestSlice(m map[pkgTest]bool) []pkgTest {
	out := make([]pkgTest, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
