// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <bpfcore/vmlinux.h>
#include <bpfcore/bpf_core_read.h>

struct sock_port_ns {
    u32 netns;
    u16 port;
    u8 _pad[2];
};

// Emit this type to autogenerated bpf2go types.
const struct sock_port_ns *__pn_unused __attribute__((unused));

static __always_inline struct sock_port_ns sock_port_ns_from_skc(const struct sock_common *skc) {
    struct sock_port_ns pn = {
        .port = BPF_CORE_READ(skc, skc_num),
        .netns = BPF_CORE_READ(skc, skc_net.net, ns.inum),
    };
    return pn;
}

static __always_inline struct sock_port_ns sock_port_ns_from_sk(const struct sock *sk) {
    struct sock_common *skc = (struct sock_common *)sk;
    return sock_port_ns_from_skc(skc);
}
