pid standalone/recommendations-v2/logs/nginx.pid;
error_log standalone/recommendations-v2/logs/error.log info;

events {}

http {
    access_log standalone/recommendations-v2/logs/access.log;

    upstream recommendations_v1_backend {
        server 127.0.0.1:8081;
    }

    include k8s/shared/recommendations-v2-server.conf;
}
